### ISSUE TITLE
Handle errors better

### ISSUE THREAD

**Issue by frol** [rshipp/python-codacycov#1]
@machadoit
I'm getting the following error when running `python-codacy-coverage` to my newly created project.

```python
$ coverage xml && CODACY_PROJECT_TOKEN=my_token_here python-codacy-coverage -r coverage.xml

2016-01-04 18:21:54,361 - INFO - Parsing report file...
2016-01-04 18:21:54,420 - INFO - Uploading report...
2016-01-04 18:21:54,424 - INFO - Starting new HTTPS connection (1): api.codacy.com
Traceback (most recent call last):
  File "/mnt/storage/www/ddots/env3/bin/python-codacy-coverage", line 11, in <module>
    sys.exit(main())
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/__init__.py", line 6, in main
    return reporter.run()
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/reporter.py", line 140, in run
    upload_report(report, CODACY_PROJECT_TOKEN, args.commit)
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/reporter.py", line 110, in upload_report
    message = json.loads(r.text)['success']
KeyError: 'success'
```

**Comment by rshipp** [comment]
See #2
