### ISSUE TITLE
Getting an error response "could not get json body." on pushing a code-coverage report

### ISSUE THREAD

**Issue by frol** [rshipp/python-codacycov#2]
@machadoit

After I had patched the issue #1, I could see that the server returned the following response:

```json
{"error":"could not get json body."}
```

Logs:

```
2016-01-04 18:23:17,235 - INFO - Parsing report file...
2016-01-04 18:23:17,292 - INFO - Uploading report...
2016-01-04 18:23:17,296 - INFO - Starting new HTTPS connection (1): api.codacy.com
{"error":"could not get json body."}
Traceback (most recent call last):
  File "/mnt/storage/www/ddots/env3/bin/python-codacy-coverage", line 11, in <module>
    sys.exit(main())
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/__init__.py", line 6, in main
    return reporter.run()
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/reporter.py", line 141, in run
    upload_report(report, CODACY_PROJECT_TOKEN, args.commit)
  File "/mnt/storage/www/ddots/env3/lib/python3.5/site-packages/codacy/reporter.py", line 111, in upload_report
    message = json.loads(r.text)['success']
KeyError: 'success'
```

**Comment by rshipp** [comment]
Hi @frol, thanks for the report! This project is managed by Codacy now, at https://github.com/codacy/python-codacy-coverage. Please open issues there instead. :smile:

**Comment by frol** [comment]
@rshipp There is no issue tracker there :(

I do use that version of a package, I believe. So I decided to put a bug report here with a CC to @machdoit, who is making changes in that fork.

**Comment by machadoit** [comment]
@frol Thanks for the report. We have spotted the issue and it's fixed by https://github.com/codacy/python-codacy-coverage/releases/tag/1.2.4

For the next release we're doing better error messages.

**Comment by frol** [comment]
@machadoit It works! Thank you!
